Update README.md
puppetlabs/puppetlabs-iis pull request #142
Opened 2017-12-11 16:59 UTC by clairecadman

2017-12-11 17:12 UTC, jpogran requested changes

2017-12-11 17:12 UTC, jpogran commented on README.md
> +The iis_application type uses a composite namevar for applicationname and sitename to uniquely identify a declaration. To use this successfully, put both the sitename and the applicationname in the t
It may be useful to put an example here, as this doesn't say it requires a `/` in between the `sitename` and `applicationname`

2017-12-13 15:55 UTC, clairecadman commented
@jpogran Please see update.

2018-01-04 14:43 UTC, jpogran approved these changes

2018-01-04 14:43 UTC, merged