(MODULES-6870) Fix Password Escaping
puppetlabs/puppetlabs-iis pull request #180
Opened 2018-08-17 18:39 UTC by RandomNoun7

This change ensures that passwords are propertly escaped before being
used in PowerShell strings.

2018-08-21 22:15 UTC, ThoughtCrhyme requested changes
The reason this PR is failing CI is because different puppet agent versions handle escape characters differently.

Puppet agent 4.10.12 (as is used in Smoke Acceptance tests) will parse a password in a manifest:
password  => Sensitive('#@\\\'454sdf')
as '#@'454sdf'

But puppet agent version of at least 5.5.2 (as is used in Full Acceptance tests) reports the same password as '#@`\`'454sdf'.

2018-08-22 16:03 UTC, michaeltlombardi commented
@ThoughtCrhyme, I think one of those reported strings is wrong? They look identical to me.

2018-08-22 16:29 UTC, ThoughtCrhyme commented
@michaeltlombardi thanks to your suggestion it's fixed now

2018-08-24 21:30 UTC, ThoughtCrhyme approved these changes

2018-08-24 21:35 UTC, merged