mergeback release 7.0.0
puppetlabs/puppetlabs-iis pull request #260
Opened 2020-01-21 10:30 UTC by lionce

2020-01-22 14:07 UTC, alexjfisher commented on CHANGELOG.md
>  All notable changes to this project will be documented in this file.
This should be removed from the `HISTORY.md` file.

2020-01-25 00:07 UTC, op-ct requested changes

2020-01-25 00:07 UTC, op-ct commented on CHANGELOG.md
> +[Full Changelog](https://github.com/puppetlabs/puppetlabs-iis/compare/v5.0.0...v6.0.0)
A git log diff [isn't a useful changelog](https://keepachangelog.com/en/1.0.0/#log-diffs), and it [doesn't meet the criteria](https://github.com/puppetlabs/puppetlabs-iis/pull/260/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eL3-L4) documented at the top of this file:

> "All notable changes to this project will be documented in this file. The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) and this project adheres to [Semantic Versioning](http://semver.org)."

1. No notable changes are documented for 6.0.0.
2. The 6.0.0 entry doesn't follow the "[Keep a Changelog](http://keepachangelog.com/en/1.0.0/)" format.
   * There's no indication what was added, fixed, or changed between 5.0.0 and 6.0.0
3. The v6.0.0 release doesn't appear to have followed [Semantic Versioning](http://semver.org/):
   * There's no indication of what API-breaking changes prompted the major version bump from 5.0.0 to 6.0.0
   * As far as I could tell after digging through the "Full Changelog" link, it appears that nothing did:
     * There were no functional code changes (just documentation under `lib/` and test updates under `spec/`).
     * The module's API didn't change.
     * The module's dependencies didn't change.

2020-01-25 00:07 UTC, op-ct commented on CHANGELOG.md
* The "All notable changes..." blurb is redundant with the same notice at the top of the file.
 * The date format for entries changed from ` - YYYY-MM-DD` (the [KACL recommendation](https://keepachangelog.com/en/1.0.0/#confusing-dates)) before v5.0.0 to ` (YYYY-MM-DD)` after v5.0.0.
 * The v5.0.0 entry doesn't have a date at all.

2020-01-25 00:07 UTC, op-ct commented on CHANGELOG.md
> +## [v7.0.0](https://github.com/puppetlabs/puppetlabs-iis/tree/v7.0.0) (2020-01-21)
This project uses [Semantic Versioning](http://semver.org)—what was the API-breaking change that bumped the major version from 6.0.0 to 7.0.0?

2020-01-27 09:27 UTC, DavidS approved these changes
mergeback approval

2020-01-27 09:27 UTC, merged