(maint) Adding MIGRATION.md for migrating from voxpupuli to puppetlabs
puppetlabs/puppetlabs-iis pull request #64
Opened 2017-04-11 00:16 UTC by hunner

2017-04-11 00:20 UTC, hunner commented
@jbondpdx It would be great if you could give this a "this is terrible and shouldn't be merged" kind of review! It's not going to be a long-living reference document.

2017-04-18 15:08 UTC, jpogran approved these changes

2017-04-19 20:22 UTC, jbondpdx requested changes
In addition to the line comments, there should be line spaces before and after all headers, and no hard line breaks within paragraphs.

2017-04-19 20:22 UTC, jbondpdx commented on MIGRATION.md
> +sslFlags 	Optional uint attribute.
typo in unit

2017-04-19 20:22 UTC, jbondpdx commented on MIGRATION.md
> +#### Parameter mapping:
should have a line space before (and after, really) headers

2017-04-19 20:22 UTC, jbondpdx commented on MIGRATION.md
> +\* The `bindings` parameter on the new `iis_site` take an array of one or more bindings as a hash and have the following keys per hash:
verb agreement; change take -> takes and have -> has

2017-04-19 20:22 UTC, jbondpdx commented on MIGRATION.md
> +The bindinginformation is in the form `<ip>:<port>`
Suggest changing "bindinginformation" to  "bindinginformation key" so it doesn't look so much like we accidentally ran the two words together.

2017-04-19 20:22 UTC, jbondpdx commented on MIGRATION.md
> +All of these properties are managed directly by the `iis_site::bindings` property and are not declared separately, as the `iis_site` and `iis::manage_binding` resources are. The following describe th
Verb agreement problem in the last sentence; for better readability, I suggest changing to:

The `iis_site::bindings` hash keys for the map are as follows:

2017-04-19 20:22 UTC, jbondpdx commented on MIGRATION.md
> +MISSING! This will be added with the proposed changes:
Is it the parameter mapping that are the proposed changes? When and how do are those changes happening? I'm confused by this one.

2017-04-19 21:15 UTC, jbondpdx approved these changes

2017-04-19 21:20 UTC, merged