(MODULES-5264) IIS: handle UNC paths
puppetlabs/puppetlabs-iis pull request #90
Opened 2017-07-21 19:40 UTC by tkishel

Prior to this commit, the IIS module:

included regular expressions that failed to a match a UNC paths
attempted to use File.exists? to test a UNC path
failed to set iis_virtual_directory physicalpath to a UNC path

Also, these issues interfered with development and testing:

ran iis_virtual_directory update() after destroy()
failed to set the iis_site :ensure attribute to :present
failed to set the iis_virtual_directory :application attribute

2017-07-31 23:59 UTC, jpogran requested changes
We should merge #93 and #91 first, because this PR changes a lot of similar files.

This PR needs to be broken up into separate commits per provider

2017-08-01 00:03 UTC, jpogran requested changes

2017-08-01 00:03 UTC, jpogran commented on lib/puppet/provider/iis_site/webadministration.rb
> +  def verify_physicalpath
We should move this to a helper method instead of having it in each provider

2017-08-01 00:03 UTC, jpogran commented on lib/puppet/provider/iis_site/webadministration.rb
> +  def is_drive_path(path)
We should move this to a helper method instead of having it in each provider

2017-08-01 00:03 UTC, jpogran commented on lib/puppet/provider/iis_virtual_directory/webadministration.rb
> +  def is_unc_path(path)
We should move this to a helper method instead of having it in each provider

2017-08-01 00:03 UTC, jpogran commented on spec/unit/puppet/type/iis_application_pool_spec.rb
> -    :clr_config_file,
If this is removed, where is it added back to test?

2017-08-01 00:03 UTC, jpogran commented on spec/unit/puppet/type/iis_site_spec.rb
> -  context "parameter :physicalpath" do
Can you explain why you removed the validation checks and tests for nil physical paths for websites? IIRC you need a physical path for a site

2017-08-01 00:04 UTC, jpogran commented on lib/puppet/provider/iis_site/webadministration.rb
> +      if site['state'] == ''
Why would state be nil here?

2017-08-01 17:22 UTC, tkishel commented on lib/puppet/provider/iis_site/webadministration.rb
> +  def verify_physicalpath
Could you recommend a file location?

2017-08-01 17:35 UTC, tkishel commented on lib/puppet/provider/iis_site/webadministration.rb
> +      if site['state'] == ''
When `ensure => present`

```
  iis_site { "test_site":
    name            => "test_site",
    ensure          => 'present',
    physicalpath    => 'c:\\inetpub\\test_site',
    applicationpool => 'DefaultApplicationPool',
  }
```

```
PS C:\Users\Administrator> Get-WebSite
                                                                                                                                                                                                       
Name             ID   State      Physical Path                  Bindings
----             --   -----      -------------                  --------
Default Web Site 1    Started    %SystemDrive%\inetpub\wwwroot  http *:80: 
test_site        2               c:\inetpub\test_site           http *:80: 
```

2017-08-01 17:39 UTC, tkishel commented on spec/unit/puppet/type/iis_application_pool_spec.rb
> -    :clr_config_file,
Line 131.

Though I've identified a potential issue here: at least one 'path' attribute is documented as accepting variables:

https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/sitedefaults/logfile/

`directory = %SystemDrive%\inetpub\logs\LogFiles`

I don't think this is true or common with physicalpath, but clr_config_file and source (iis_feature)?

2017-08-01 17:49 UTC, tkishel commented on spec/unit/puppet/type/iis_site_spec.rb
> -  context "parameter :physicalpath" do
I'll restore that. Mislead by: 
https://technet.microsoft.com/en-us/library/hh867858(v=wps.630).aspx

2017-08-01 17:50 UTC, tkishel commented on spec/unit/puppet/type/iis_site_spec.rb
> -  context "parameter :physicalpath" do
```
-PhysicalPath<String>
Required? | false
```

2017-08-01 17:52 UTC, tkishel commented
I will need advice on reverting and breaking into separate commits per provider.

2017-08-02 01:22 UTC, tkishel commented
I rebased and split my previous commit, created lib/puppet/provider/iis_common.rb for helper methods, and added spec tests. Please let me know if this is what you're expecting!

2017-08-09 00:12 UTC, tkishel commented
I could rebase this from master, or close and recreate, or back away slowly ... just let me know.

2017-08-16 21:11 UTC, tkishel commented
Closing in favor of a new PR (104) with a cleaner scope.

2017-08-16 21:11 UTC, closed without merging