(MODULES-5344) iis_virtual_directory handle slashes in name
puppetlabs/puppetlabs-iis pull request #91
Opened 2017-07-27 18:39 UTC by tkishel

Prior to this commit, iis_virtual_directory was not idempotent when the name
attribute contained slashes.

iis_virtual_directory uses the PowerShell New-WebVirtualDirectory command.
New-VirtualDirectory uses Name to set Path, and Path may contain slashes.

With this commit, iis_virtual_directory is idempotent when name contains
backward slashes. Due to the behaviour of Get-Item and Get-WebVirtualDirectory,
name may not contain forward slashes, as documented in the associated ticket.

2017-07-27 19:18 UTC, tkishel commented
(Correctly handing slashes allows users to specify nested virtual directories.)

```
iis_site { "test_site":
  name            => "test_site",
  ensure          => 'present',
  physicalpath    => 'c:\\inetpub\\test_site',
  applicationpool => 'DefaultApplicationPool',
} ->
iis_virtual_directory{ "test_vdir":
  ensure          => 'present',
  sitename        => "test_site",
  physicalpath    => 'c:\\inetpub\\test_vdir',
} ->
iis_virtual_directory { 'test_vdir\deeper':
  name         => 'test_vdir\deeper',
  ensure	 => 'present',
  sitename     => 'test_site',
  physicalpath => 'c:\\inetpub\\deeper',
}
```

2017-07-31 20:26 UTC, jpogran requested changes
This will need an acceptance test to be merged, but otherwise looks good

2017-07-31 20:26 UTC, jpogran commented on lib/puppet/provider/templates/webadministration/_getvirtualdirectories.ps1.erb
> +} | ConvertTo-Json -Depth 10
Missing empty newline

2017-07-31 20:26 UTC, jpogran commented on lib/puppet/provider/templates/webadministration/_getvirtualdirectories.ps1.erb
> +    sitename     = $sitename
Don't move a line to just move a line

2017-07-31 20:26 UTC, jpogran commented on lib/puppet/provider/templates/webadministration/_getvirtualdirectories.ps1.erb
> +    application  = $application
Don't move a line to just move a line

2017-07-31 23:57 UTC, jpogran commented
Added spec tests according to example in ticket, but these seem to be failing locally. Will have to investigate

2017-08-01 17:10 UTC, tkishel commented
Does the spec test need the iis_site "test_site" (referenced via sitename) defined?

2017-08-01 17:16 UTC, tkishel commented on lib/puppet/provider/templates/webadministration/_getvirtualdirectories.ps1.erb
> +    application  = $application
I'd like to make the case that including initializing all for variables at the top and processing them in a specific order.

2017-10-23 21:45 UTC, Iristyle commented
Ad-hoc was triggered at https://jenkins-master-prod-1.delivery.puppetlabs.net/view/All/job/forge-windows_puppetlabs-iis_init-manual-parameters_adhoc/18/

2017-10-24 13:54 UTC, jpogran approved these changes

2017-10-24 13:55 UTC, merged